version: "3"

services:
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile.dev
    ports:
      - 6565:80
    volumes:
      - ./src/api:/app
    working_dir: /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    command: ["dotnet", "watch", "run", "--non-interactive", "--launch-profile=watch"]
