# Base values: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml

# define default database user, name, and password for PostgreSQL deployment
auth:
  enablePostgresUser: true
  postgresPassword: "StrongPassword"
  username: "app1"
  password: "AppPassword"
  database: "app_db"

# The postgres helm chart deployment will be using PVC postgresql-data-claim
primary:
  persistence:
    enabled: true
    existingClaim: postgres-pvc

volumePermissions:
  enabled: true
